export const ICON_MAP = {
  UPVOTE: "arrow.up",
  DOWNVOTE: "arrow.down",
  REPLY: "bubble.left",
  SAVE: "bookmark",
  SHARE: "square.and.arrow.up",
  HIDE: "eye.slash",
  REPORT_POST: "flag",
  SUBSCRIBE: "heart",
  BLOCK_USER: "person.crop.circle.badge.xmark",
  USER_AVATAR: "person.circle",
  CLOCK: "clock",
  EDIT: "square.and.pencil",
  DELETE: "trash",
  COPY: "doc.on.doc",
  LINK: "link",
  BLOCK_COMMUNITY: "xmark.circle",
};
