export const ICON_MAP = {
  UPVOTE: "arrow.up",
  DOWNVOTE: "arrow.down",
  REPLY: "bubble.left",
  SAVE: "bookmark",
  SHARE: "square.and.arrow.up",
  HIDE: "eye.slash",
  REPORT_POST: "flag",
  SUBSCRIBE: "heart",
  BLOCK_USER: "person.crop.circle.badge.xmark",
  USER_AVATAR: "person.circle",
  CLOCK: "clock",
  EDIT: "square.and.pencil",
  DELETE: "trash",
  COPY: "doc.on.doc",
  LINK: "link",
  BLOCK: "xmark.circle",
  FILTERS: "eye.slash",
  GLOBE: "globe",
  LOCATION: "location",
  HEART: "heart",
  CALENDAR: "calendar",
  TROPHY: "trophy",
  FLAME: "flame",
  BOLT: "bolt",
  ALARM: "alarm",
  MOST_COMMENTS: "bubble.left.and.bubble.right",
  NEW_COMMENTS: "star.bubble",
  HOURGLASS: "hourglass",
  CHEVRON: {
    RIGHT: "chevron.right",
  },
  MORE_OPTIONS: "ellipsis",
  POST_SIZE: {
    COMPACT: "list.bullet",
    LARGE: "list.bullet.below.rectangle",
  },
};
