import {
  ArrowDown,
  ArrowUp,
  Bookmark,
  BookmarkCheck,
  Box,
  CalendarCheck,
  CalendarDays,
  CalendarMinus,
  CalendarPlus,
  CalendarRange,
  CircleEllipsis,
  Clock1,
  Clock11,
  Clock6,
  Flame,
  Globe,
  Heart,
  MailOpen,
  MessageCircle,
  Shield,
  Zap,
} from '@tamagui/lucide-icons';

export const IconMap = {
  dots: CircleEllipsis,
  upvote: ArrowUp,
  downvote: ArrowDown,
  undefined: CircleEllipsis,
  reply: MessageCircle,
  comment: MessageCircle,
  save: Bookmark,
  read: MailOpen,
  saved: BookmarkCheck,
  Active: Zap,
  Hot: Flame,
  New: Clock1,
  Old: CalendarMinus,
  Top: ArrowUp,
  TopHour: Clock1,
  TopSixHour: Clock6,
  TopTwelveHour: Clock11,
  TopDay: CalendarRange,
  TopWeek: CalendarDays,
  TopMonth: CalendarCheck,
  TopYear: CalendarPlus,
  TopAll: ArrowUp,
  MostComments: MessageCircle,
  NewComments: MessageCircle,
  Moderated: Shield,
  Local: Box,
  Subscribed: Heart,
  All: Globe,
};

export type IconType = keyof typeof IconMap;
