export type PostContextMenuOption =
  | 'inline'
  | 'reply'
  | 'share'
  | 'shareImage'
  | 'saveImage'
  | 'shareLink'
  | 'edit'
  | 'delete'
  | 'remove'
  | 'upvote'
  | 'downvote'
  | 'report'
  | 'copyImage'
  | 'copyText'
  | 'blockCreator'
  | 'blockCommunity';
