name: Lint

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 18

    - name: Install Node deps
      run: yarn install

    - name: Run lint
      uses: wearerequired/lint-action@v2
      with:
        eslint: true
        prettier: true


